/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FS_H_RPCGEN
#define _FS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int buffer_len;
	char *buffer_val;
} buffer;

typedef char *filename;

struct read_file_1_argument {
	filename arg1;
	int arg2;
	int arg3;
};
typedef struct read_file_1_argument read_file_1_argument;

struct write_file_1_argument {
	filename arg1;
	buffer arg2;
	int arg3;
};
typedef struct write_file_1_argument write_file_1_argument;

#define FS_PROG 555555555
#define FS_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define read_file 1
extern  buffer * read_file_1(filename , int , int , CLIENT *);
extern  buffer * read_file_1_svc(filename , int , int , struct svc_req *);
#define write_file 2
extern  int * write_file_1(filename , buffer , int , CLIENT *);
extern  int * write_file_1_svc(filename , buffer , int , struct svc_req *);
extern int fs_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define read_file 1
extern  buffer * read_file_1();
extern  buffer * read_file_1_svc();
#define write_file 2
extern  int * write_file_1();
extern  int * write_file_1_svc();
extern int fs_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_buffer (XDR *, buffer*);
extern  bool_t xdr_filename (XDR *, filename*);
extern  bool_t xdr_read_file_1_argument (XDR *, read_file_1_argument*);
extern  bool_t xdr_write_file_1_argument (XDR *, write_file_1_argument*);

#else /* K&R C */
extern bool_t xdr_buffer ();
extern bool_t xdr_filename ();
extern bool_t xdr_read_file_1_argument ();
extern bool_t xdr_write_file_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FS_H_RPCGEN */
