/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "fs.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
read_1(read_args *argp, read_ret *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, READ,
		(xdrproc_t) xdr_read_args, (caddr_t) argp,
		(xdrproc_t) xdr_read_ret, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
write_1(write_args *argp, long *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, WRITE,
		(xdrproc_t) xdr_write_args, (caddr_t) argp,
		(xdrproc_t) xdr_long, (caddr_t) clnt_res,
		TIMEOUT));
}
