/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fs.h"

bool_t
xdr_buffer (XDR *xdrs, buffer *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->buffer_val, (u_int *) &objp->buffer_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_filename (XDR *xdrs, filename *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 50))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_read_file_1_argument (XDR *xdrs, read_file_1_argument *objp)
{
	 if (!xdr_filename (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_write_file_1_argument (XDR *xdrs, write_file_1_argument *objp)
{
	 if (!xdr_filename (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_buffer (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}
